# Generated by Django 3.1.4 on 2020-12-12 07:39

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=music.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
